name: Push Tweets to Google Chat

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/516998943557/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'twitter-bot@stellar-store-500600-v1.iam.gserviceaccount.com'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute script
        env:
          CHAT_SPACE: ${{ secrets.CHAT_SPACE }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: python bot.py

      - name: Commit state file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update last processed tweet IDs"
          file_pattern: last_ids.json
